<?php

namespace HassanDomeDenea\HddLaravelHelpers;

use HassanDomeDenea\HddLaravelHelpers\Commands\AddPermissionsCommand;
use HassanDomeDenea\HddLaravelHelpers\Commands\HddLaravelHelpersCommand;
use Illuminate\Support\Facades\Route;
use Spatie\LaravelPackageTools\Exceptions\InvalidPackage;
use Spatie\LaravelPackageTools\Package;
use Spatie\LaravelPackageTools\PackageServiceProvider;

class HddLaravelHelpersServiceProvider extends PackageServiceProvider
{
    /**
     * @throws InvalidPackage
     */
    public function register(): void
    {
        Route::macro('apiResourceMany', function (string $name, string $controller, ?array $only = null) {
            if ($only === null) {
                $only = ['search', 'storeMany',  'updateMany', 'destroyMany'];
            }
            if (in_array('search', $only)) {
                Route::get($name.'/search', [$controller, 'search'])->name($name.'.search');
            }
            if (in_array('storeMany', $only)) {
                Route::post($name.'/many', [$controller, 'storeMany'])->name($name.'.store-many');
            }
            if (in_array('updateMany', $only)) {
                Route::put($name, [$controller, 'updateMany'])->name($name.'.update-many');
            }
            if (in_array('destroyMany', $only)) {
                Route::delete($name, [$controller, 'destroyMany'])->name($name.'.destroy-many');
            }

            return Route::apiResource($name, $controller);
        });
        parent::register(); // TODO: Change the autogenerated stub
    }

    public function boot(): self
    {
        if ($this->app->runningInConsole()) {
         /*   $this->commands([
                InstallCommand::class,
            ]);*/
        }
        return parent::boot(); // TODO: Change the autogenerated stub
    }

    public function configurePackage(Package $package): void
    {
        /*
         * This class is a Package Service Provider
         *
         * More info: https://github.com/spatie/laravel-package-tools
         */
        $package
            ->name('hddLaravelHelpers')
            ->hasConfigFile('hdd-laravel-helpers')
//            ->hasViews()
//            ->hasMigration('create_hddlaravelhelpers_table')
            ->hasCommands(
                [
                    AddPermissionsCommand::class,
                    HddLaravelHelpersCommand::class
                ]
            );
    }
}
